version: '3.8'

services:

  # server:
  #   build:
  #     dockerfile: test.Dockerfile
  #     context: .
  #   command: ./target/debug/what_meme_it_is
  #   env_file:
  #     - .env
  #   ports:
  #     - ${PORT}:${PORT}
    # tty: true
    # stdin_open: true

  db:
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - ${PGPORT}:${PGPORT}
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

