version: '3.8'

services:

  server:
    build:
      dockerfile: test.Dockerfile
      context: .
    command: ./what_meme_it_is
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}

  db:
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}

