version: "3.8"

services:
  server:
    build:
      dockerfile: dev.Dockerfile
      context: .
    command: cargo run
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}

  db:
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - ${PGPORT}:${PGPORT}
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
